### Generated by rprotoc. DO NOT EDIT!
### <proto file: ErrorGPB.proto>
# message ErrorGPB
# {
#     required string error_text = 1;
#     required int32  error_code = 2;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class ErrorGPB < ::Protobuf::Message
  defined_in __FILE__
  required :string, :error_text, 1
  required :int32, :error_code, 2
end