### Generated by rprotoc. DO NOT EDIT!
### <proto file: LoginGPB.proto>
# import "ErrorGPB.proto";
# 
# //SignUp
# message SignUpRequest
# {
#     required string macAddress = 1;
# }
# 
# message SignUpResponse
# {
#     optional ErrorGPB error = 1;
#     required string username = 2;
# }
# 
# message PasswordRequest
# {
#     required string password = 1;
# }
# 
# message PasswordResponse
# {
#     optional ErrorGPB error = 1;
# }
# 
# //login
# message LoginRequest
# {
# 	required string username = 1;
# 	required string password = 2;
# }
# 
# message LoginResponse
# {
#     optional ErrorGPB error = 1;
# }
# 
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

require 'ErrorGPB.pb'
class SignUpRequest < ::Protobuf::Message
  defined_in __FILE__
  required :string, :macAddress, 1
end
class SignUpResponse < ::Protobuf::Message
  defined_in __FILE__
  optional :ErrorGPB, :error, 1
  required :string, :username, 2
end
class PasswordRequest < ::Protobuf::Message
  defined_in __FILE__
  required :string, :password, 1
end
class PasswordResponse < ::Protobuf::Message
  defined_in __FILE__
  optional :ErrorGPB, :error, 1
end
class LoginRequest < ::Protobuf::Message
  defined_in __FILE__
  required :string, :username, 1
  required :string, :password, 2
end
class LoginResponse < ::Protobuf::Message
  defined_in __FILE__
  optional :ErrorGPB, :error, 1
end